# Generated by Django 5.2 on 2025-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_athlete_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(),
        ),
    ]
