# Generated by Django 5.2 on 2025-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализация'), ('in_progress', 'Старт'), ('finished', 'Стоп')], default='init'),
        ),
    ]
