# Generated by Django 5.2 on 2025-10-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
