# Generated by Django 5.2 on 2025-10-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(default='Unnamed challenge', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('athlete', 'full_name')},
        ),
    ]
