# Generated by Django 5.2 on 2025-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_challenge_athlete_alter_challenge_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('lontitude', models.FloatField()),
            ],
        ),
    ]
