# Generated by Django 5.2 on 2025-10-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='lontitude',
            new_name='longitude',
        ),
    ]
