# Generated by Django 5.2 on 2025-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_rename_lontitude_position_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='position',
            name='longitude',
        ),
        migrations.AddField(
            model_name='run',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
