# Generated by Django 5.2 on 2025-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_remove_position_latitude_remove_position_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='run',
            name='longitude',
        ),
        migrations.AddField(
            model_name='position',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
