# Generated by Django 5.2 on 2025-10-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_remove_run_latitude_remove_run_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_run.run'),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
