# Generated by Django 5.2 on 2025-11-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_position_run_alter_position_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
